const javascriptComposition = () => {
    console.log('composition in javascript');

    const preparing = () => ({ prepare: () => console.log('Preparing...') });
    const serving = () => ({ serve: () => console.log('Ready to serve!\n\n') });
    const buttering = () => ({ butter: () => console.log('Buttering...') });
    const addingFlatBread = () => ({ addFlatBread: () => console.log('Adding flat bread...') });
    const addingBunBread = () => ({ addBunBread: () => console.log('Adding bun bread...') });
    const addingLongBread = () => ({ addLongBread: () => console.log('Adding long bread...') });
    const addingSausage = () => ({ addSausage: () => console.log('Adding sausage...') });
    const addingHotSauce = () => ({ addHotSauce: () => console.log('Adding hot sauce...') });
    const addingKetchup = () => ({ addKetchup: () => console.log('Adding ketchup...') });
    const addingMayonnaise = () => ({ addMayonnaise: () => console.log('Adding mayonnaise...') });
    const addingMushroom = () => ({ addMushroom: () => console.log('Adding mushroom...') });
    const addingCheese = () => ({ addCheese: () => console.log('Adding cheese...') });
    const addingBeefPatty = () => ({ addBeefPatty: () => console.log('Adding beef patty...') });
    const addingEgg = () => ({ addEgg: () => console.log('Adding egg...') });
    const addingLettuce = () => ({ addLettuce: () => console.log('Adding lettuce...') });
    const addingTomatto = () => ({ addTomatto: () => console.log('Adding tomatto...') });
    const addingCucumber = () => ({ addCucumber: () => console.log('Adding cucumber...') });
    const addingOnion = () => ({ addOnion: () => console.log('Adding onion...') });
    const baking = () => ({ bake: () => console.log('Baking...') });
    const frying = () => ({ fry: () => console.log('Frying...') });

    const createOrdinaryPizza = () => ({ ...preparing(), ...addingFlatBread(), ...buttering(), ...serving() });
    const createOrdinaryBurger = () => ({ ...preparing(), ...addingBunBread(), ...buttering(), ...serving() });
    const createOrdinaryHotdog = () => ({ ...preparing(), ...addingLongBread(), ...buttering(), ...addingSausage(), ...frying(), ...addingHotSauce(), ...addingKetchup(), ...addingMayonnaise(), ...serving() });
    const createSausageCheesePizza = () => ({ ...createOrdinaryPizza(), ...addingSausage(), ...frying(), ...addingCheese(), ...addingKetchup(), ...addingHotSauce() });
    const createSausageMushroomCheesePizza = () => ({ ...createOrdinaryPizza(), ...addingSausage(), ...frying(), ...addingMushroom(), ...addingCheese(), ...addingKetchup(), ...addingHotSauce() });
    const createSausageMushroomBeefCheesePizza = () => ({ ...createOrdinaryPizza(), ...addingSausage(), ...frying(), ...addingBeefPatty(), ...frying(), ...addingMushroom(), ...addingCheese(), ...addingKetchup(), ...addingHotSauce() });
    const createBeefCheeseBurger = () => ({ ...createOrdinaryBurger(), ...addingBeefPatty(), ...frying(), ...addingCheese(), ...addingLettuce(), ...addingTomatto(), ...addingOnion(), ...addingCucumber(), ...addingKetchup(), ...addingHotSauce() });
    const createEggCheeseBurger = () => ({ ...createOrdinaryBurger(), ...addingEgg(), ...frying(), ...addingCheese(), ...addingLettuce(), ...addingTomatto(), ...addingOnion(), ...addingCucumber(), ...addingKetchup(), ...addingHotSauce() });

    const davesSausageCheesePizza = createSausageCheesePizza();
    davesSausageCheesePizza.prepare(); // Preparing...
    davesSausageCheesePizza.addFlatBread(); // Adding flat bread...
    davesSausageCheesePizza.butter(); // Buttering...
    davesSausageCheesePizza.addSausage(); // Adding sausage...
    davesSausageCheesePizza.fry(); // Frying...
    davesSausageCheesePizza.addCheese(); // Adding cheese...
    davesSausageCheesePizza.addKetchup(); // Adding ketchup...
    davesSausageCheesePizza.addHotSauce(); // Adding hot sauce...
    davesSausageCheesePizza.serve(); // Ready to serve!

    const alisaSausageCheesePizza = createSausageCheesePizza();
    alisaSausageCheesePizza.prepare(); // Preparing...
    alisaSausageCheesePizza.addFlatBread(); // Adding flat bread...
    alisaSausageCheesePizza.butter(); // Buttering...
    alisaSausageCheesePizza.addSausage(); // Adding sausage...
    alisaSausageCheesePizza.fry(); // Frying...
    alisaSausageCheesePizza.addCheese(); // Adding cheese...
    alisaSausageCheesePizza.addKetchup(); // Adding ketchup...
    alisaSausageCheesePizza.addHotSauce(); // Adding hot sauce...
    alisaSausageCheesePizza.serve(); // Ready to serve!

    const triviaBeefCheeseBurger = createBeefCheeseBurger();
    triviaBeefCheeseBurger.prepare(); // Preparing...
    triviaBeefCheeseBurger.addBunBread(); // Adding bun bread...
    triviaBeefCheeseBurger.butter(); // Buttering...
    triviaBeefCheeseBurger.addBeefPatty(); // Adding beef patty...
    triviaBeefCheeseBurger.fry(); // Frying...
    triviaBeefCheeseBurger.addCheese(); // Adding cheese...
    triviaBeefCheeseBurger.addLettuce(); // Adding lettuce...
    triviaBeefCheeseBurger.addTomatto(); // Adding tomatto...
    triviaBeefCheeseBurger.addOnion(); // Adding onion...
    triviaBeefCheeseBurger.addCucumber(); // Adding cucumber...
    triviaBeefCheeseBurger.addKetchup(); // Adding ketchup...
    triviaBeefCheeseBurger.addHotSauce(); // Adding hot sauce...
    triviaBeefCheeseBurger.addBunBread(); // Adding bun bread...
    triviaBeefCheeseBurger.serve(); // Ready to serve!

    const euniceBeefCheeseBurger = createEggCheeseBurger();
    euniceBeefCheeseBurger.prepare(); // Preparing...
    euniceBeefCheeseBurger.addBunBread(); // Adding bun bread...
    euniceBeefCheeseBurger.butter(); // Buttering...
    euniceBeefCheeseBurger.addEgg(); // Adding egg...
    euniceBeefCheeseBurger.fry(); // Frying...
    euniceBeefCheeseBurger.addCheese(); // Adding cheese...
    euniceBeefCheeseBurger.addLettuce(); // Adding lettuce...
    euniceBeefCheeseBurger.addTomatto(); // Adding tomatto...
    euniceBeefCheeseBurger.addOnion(); // Adding onion...
    euniceBeefCheeseBurger.addCucumber(); // Adding cucumber...
    euniceBeefCheeseBurger.addKetchup(); // Adding ketchup...
    euniceBeefCheeseBurger.addHotSauce(); // Adding hot sauce...
    euniceBeefCheeseBurger.addBunBread(); // Adding bun bread...
    euniceBeefCheeseBurger.serve(); // Ready to serve!

    const angelHotDog = createOrdinaryHotdog();
    angelHotDog.prepare(); // Preparing...
    angelHotDog.addLongBread(); // Adding long bread...
    angelHotDog.butter(); // Buttering...
    angelHotDog.addSausage(); // Adding sausage...
    angelHotDog.fry(); // Frying...
    angelHotDog.addHotSauce(); // Adding hot sauce...
    angelHotDog.addKetchup(); // Adding ketchup...
    angelHotDog.addMayonnaise(); // Adding mayonnaise...
    angelHotDog.serve(); // Ready to serve!
};

export default javascriptComposition;
