const javascriptComposition = () => {
    console.log('Composition in Javascript\n\n');

    const preparing = () => ({ prepare: () => console.log('preparing...') });
    const serving = () => ({ serve: () => console.log('ready to serve!\n\n') });
    const buttering = () => ({ butter: () => console.log('buttering...') });
    const addingFlatBread = () => ({ addFlatBread: () => console.log('adding flat bread...') });
    const addingBunBread = () => ({ addBunBread: () => console.log('adding bun bread...') });
    const addingLongBread = () => ({ addLongBread: () => console.log('adding long bread...') });
    const addingSausage = () => ({ addSausage: () => console.log('adding sausage...') });
    const addingHotSauce = () => ({ addHotSauce: () => console.log('adding hot sauce...') });
    const addingKetchup = () => ({ addKetchup: () => console.log('adding ketchup...') });
    const addingMayonnaise = () => ({ addMayonnaise: () => console.log('adding mayonnaise...') });
    const addingMushroom = () => ({ addMushroom: () => console.log('adding mushroom...') });
    const addingCheese = () => ({ addCheese: () => console.log('adding cheese...') });
    const addingBeefPatty = () => ({ addBeefPatty: () => console.log('adding beef patty...') });
    const addingEgg = () => ({ addEgg: () => console.log('adding egg...') });
    const addingLettuce = () => ({ addLettuce: () => console.log('adding lettuce...') });
    const addingTomatto = () => ({ addTomatto: () => console.log('adding tomatto...') });
    const addingCucumber = () => ({ addCucumber: () => console.log('adding cucumber...') });
    const addingOnion = () => ({ addOnion: () => console.log('adding onion...') });
    const baking = () => ({ bake: () => console.log('baking...') });
    const frying = () => ({ fry: () => console.log('frying...') });

    const createOrdinaryPizza = () => ({ ...preparing(), ...addingFlatBread(), ...buttering(), ...serving() });
    const createOrdinaryBurger = () => ({ ...preparing(), ...addingBunBread(), ...buttering(), ...serving() });
    const createOrdinaryHotdog = () => ({ ...preparing(), ...addingLongBread(), ...buttering(), ...addingSausage(), ...frying(), ...addingHotSauce(), ...addingKetchup(), ...addingMayonnaise(), ...serving() });
    const createSausageCheesePizza = () => ({ ...createOrdinaryPizza(), ...addingSausage(), ...frying(), ...addingCheese(), ...addingKetchup(), ...addingHotSauce() });
    const createSausageMushroomCheesePizza = () => ({ ...createOrdinaryPizza(), ...addingSausage(), ...frying(), ...addingMushroom(), ...addingCheese(), ...addingKetchup(), ...addingHotSauce() });
    const createSausageMushroomBeefCheesePizza = () => ({ ...createOrdinaryPizza(), ...addingSausage(), ...frying(), ...addingBeefPatty(), ...frying(), ...addingMushroom(), ...addingCheese(), ...addingKetchup(), ...addingHotSauce() });
    const createBeefCheeseBurger = () => ({ ...createOrdinaryBurger(), ...addingBeefPatty(), ...frying(), ...addingCheese(), ...addingLettuce(), ...addingTomatto(), ...addingOnion(), ...addingCucumber(), ...addingKetchup(), ...addingHotSauce() });
    const createEggCheeseBurger = () => ({ ...createOrdinaryBurger(), ...addingEgg(), ...frying(), ...addingCheese(), ...addingLettuce(), ...addingTomatto(), ...addingOnion(), ...addingCucumber(), ...addingKetchup(), ...addingHotSauce() });

    const davesSausageCheesePizza = createSausageCheesePizza();
    davesSausageCheesePizza.prepare(); // preparing...
    davesSausageCheesePizza.addFlatBread(); // adding flat bread...
    davesSausageCheesePizza.butter(); // buttering...
    davesSausageCheesePizza.addSausage(); // adding sausage...
    davesSausageCheesePizza.fry(); // frying...
    davesSausageCheesePizza.addCheese(); // adding cheese...
    davesSausageCheesePizza.addKetchup(); // adding ketchup...
    davesSausageCheesePizza.addHotSauce(); // adding hot sauce...
    davesSausageCheesePizza.serve(); // ready to serve!

    const alisaSausageCheesePizza = createSausageCheesePizza();
    alisaSausageCheesePizza.prepare(); // preparing...
    alisaSausageCheesePizza.addFlatBread(); // adding flat bread...
    alisaSausageCheesePizza.butter(); // buttering...
    alisaSausageCheesePizza.addSausage(); // adding sausage...
    alisaSausageCheesePizza.fry(); // frying...
    alisaSausageCheesePizza.addCheese(); // adding cheese...
    alisaSausageCheesePizza.addKetchup(); // adding ketchup...
    alisaSausageCheesePizza.addHotSauce(); // adding hot sauce...
    alisaSausageCheesePizza.serve(); // ready to serve!

    const triviaBeefCheeseBurger = createBeefCheeseBurger();
    triviaBeefCheeseBurger.prepare(); // preparing...
    triviaBeefCheeseBurger.addBunBread(); // adding bun bread...
    triviaBeefCheeseBurger.butter(); // buttering...
    triviaBeefCheeseBurger.addBeefPatty(); // adding beef patty...
    triviaBeefCheeseBurger.fry(); // frying...
    triviaBeefCheeseBurger.addCheese(); // adding cheese...
    triviaBeefCheeseBurger.addLettuce(); // adding lettuce...
    triviaBeefCheeseBurger.addTomatto(); // adding tomatto...
    triviaBeefCheeseBurger.addOnion(); // adding onion...
    triviaBeefCheeseBurger.addCucumber(); // adding cucumber...
    triviaBeefCheeseBurger.addKetchup(); // adding ketchup...
    triviaBeefCheeseBurger.addHotSauce(); // adding hot sauce...
    triviaBeefCheeseBurger.addBunBread(); // adding bun bread...
    triviaBeefCheeseBurger.serve(); // ready to serve!

    const euniceBeefCheeseBurger = createEggCheeseBurger();
    euniceBeefCheeseBurger.prepare(); // preparing...
    euniceBeefCheeseBurger.addBunBread(); // adding bun bread...
    euniceBeefCheeseBurger.butter(); // buttering...
    euniceBeefCheeseBurger.addEgg(); // adding egg...
    euniceBeefCheeseBurger.fry(); // frying...
    euniceBeefCheeseBurger.addCheese(); // adding cheese...
    euniceBeefCheeseBurger.addLettuce(); // adding lettuce...
    euniceBeefCheeseBurger.addTomatto(); // adding tomatto...
    euniceBeefCheeseBurger.addOnion(); // adding onion...
    euniceBeefCheeseBurger.addCucumber(); // adding cucumber...
    euniceBeefCheeseBurger.addKetchup(); // adding ketchup...
    euniceBeefCheeseBurger.addHotSauce(); // adding hot sauce...
    euniceBeefCheeseBurger.addBunBread(); // adding bun bread...
    euniceBeefCheeseBurger.serve(); // ready to serve!

    const angelHotDog = createOrdinaryHotdog();
    angelHotDog.prepare(); // preparing...
    angelHotDog.addLongBread(); // adding long bread...
    angelHotDog.butter(); // buttering...
    angelHotDog.addSausage(); // adding sausage...
    angelHotDog.fry(); // frying...
    angelHotDog.addHotSauce(); // adding hot sauce...
    angelHotDog.addKetchup(); // adding ketchup...
    angelHotDog.addMayonnaise(); // adding mayonnaise...
    angelHotDog.serve(); // ready to serve!
};

export default javascriptComposition;
