def python_composition():
    print('Composition in Python\n')

    preparing = lambda: {'prepare': lambda: print('preparing...')}
    serving = lambda: {'serve': lambda: print('ready to serve!\n\n')}
    buttering = lambda: {'butter': lambda: print('buttering...')}
    adding_flat_bread = lambda: {'add_flat_bread': lambda: print('adding flat bread...')}
    adding_bun_bread = lambda: {'add_bun_bread': lambda: print('adding bun bread...')}
    adding_long_bread = lambda: {'add_long_bread': lambda: print('adding long bread...')}
    adding_sausage = lambda: {'add_sausage': lambda: print('adding sausage...')}
    adding_hot_sauce = lambda: {'add_hot_sauce': lambda: print('adding hot sauce...')}
    adding_ketchup = lambda: {'add_ketchup': lambda: print('adding ketchup...')}
    adding_mayonnaise = lambda: {'add_mayonnaise': lambda: print('adding mayonnaise...')}
    adding_mushroom = lambda: {'add_mushroom': lambda: print('adding mushroom...')}
    adding_cheese = lambda: {'add_cheese': lambda: print('adding cheese...')}
    adding_beef_patty = lambda: {'add_beef_patty': lambda: print('adding beef patty...')}
    adding_egg = lambda: {'add_egg': lambda: print('adding egg...')}
    adding_lettuce = lambda: {'add_lettuce': lambda: print('adding lettuce...')}
    adding_tomatto = lambda: {'add_tomatto': lambda: print('adding tomatto...')}
    adding_cucumber = lambda: {'add_cucumber': lambda: print('adding cucumber...')}
    adding_onion = lambda: {'add_onion': lambda: print('adding onion...')}
    baking = lambda: {'bake': lambda: print('baking...')}
    frying = lambda: {'fry': lambda: print('frying...')}

    create_ordinary_pizza = lambda: {**preparing(), **adding_flat_bread(), **buttering(), **serving()}
    create_ordinary_burger = lambda: {**preparing(), **adding_bun_bread(), **buttering(), **serving()}
    create_ordinary_hotdog = lambda: {**preparing(), **adding_long_bread(), **buttering(), **adding_sausage(), **frying(), **adding_hot_sauce(), **adding_ketchup(), **adding_mayonnaise(), **serving()}
    create_sausage_cheese_pizza = lambda: {**create_ordinary_pizza(), **adding_sausage(), **frying(), **adding_cheese(), **adding_ketchup(), **adding_hot_sauce()}
    create_sausage_mushroom_cheese_pizza = lambda: {**create_ordinary_pizza(), **adding_sausage(), **frying(), **adding_mushroom(), **adding_cheese(), **adding_ketchup(), **adding_hot_sauce()}
    create_sausage_mushroom_beef_cheese_pizza = lambda: {**create_ordinary_pizza(), **adding_sausage(), **frying(), **adding_beef_patty(), **frying(), **adding_mushroom(), **adding_cheese(), **adding_ketchup(), **adding_hot_sauce()}
    create_beef_cheese_burger = lambda: {**create_ordinary_burger(), **adding_beef_patty(), **frying(), **adding_cheese(), **adding_lettuce(), **adding_tomatto(), **adding_onion(), **adding_cucumber(), **adding_ketchup(), **adding_hot_sauce()}
    create_egg_cheese_burger = lambda: {**create_ordinary_burger(), **adding_egg(), **frying(), **adding_cheese(), **adding_lettuce(), **adding_tomatto(), **adding_onion(), **adding_cucumber(), **adding_ketchup(), **adding_hot_sauce()}

    daves_sausage_cheese_pizza = create_sausage_cheese_pizza()
    daves_sausage_cheese_pizza['prepare']()  # preparing...
    daves_sausage_cheese_pizza['add_flat_bread']()  # adding flat bread...
    daves_sausage_cheese_pizza['butter']()  # buttering...
    daves_sausage_cheese_pizza['add_sausage']()  # adding sausage...
    daves_sausage_cheese_pizza['fry']()  # frying...
    daves_sausage_cheese_pizza['add_cheese']()  # adding cheese...
    daves_sausage_cheese_pizza['add_ketchup']()  # adding ketchup...
    daves_sausage_cheese_pizza['add_hot_sauce']()  # adding hot sauce...
    daves_sausage_cheese_pizza['serve']()  # ready to serve!

    alisa_sausage_cheese_pizza = create_sausage_cheese_pizza()
    alisa_sausage_cheese_pizza['prepare']()  # preparing...
    alisa_sausage_cheese_pizza['add_flat_bread']()  # adding flat bread...
    alisa_sausage_cheese_pizza['butter']()  # buttering...
    alisa_sausage_cheese_pizza['add_sausage']()  # adding sausage...
    alisa_sausage_cheese_pizza['fry']()  # frying...
    alisa_sausage_cheese_pizza['add_cheese']()  # adding cheese...
    alisa_sausage_cheese_pizza['add_ketchup']()  # adding ketchup...
    alisa_sausage_cheese_pizza['add_hot_sauce']()  # adding hot sauce...
    alisa_sausage_cheese_pizza['serve']()  # ready to serve!

    trivia_beef_cheese_burger = create_beef_cheese_burger()
    trivia_beef_cheese_burger['prepare']()  # preparing...
    trivia_beef_cheese_burger['add_bun_bread']()  # adding bun bread...
    trivia_beef_cheese_burger['butter']()  # buttering...
    trivia_beef_cheese_burger['add_beef_patty']()  # adding beef patty...
    trivia_beef_cheese_burger['fry']()  # frying...
    trivia_beef_cheese_burger['add_cheese']()  # adding cheese...
    trivia_beef_cheese_burger['add_lettuce']()  # adding lettuce...
    trivia_beef_cheese_burger['add_tomatto']()  # adding tomatto...
    trivia_beef_cheese_burger['add_onion']()  # adding onion...
    trivia_beef_cheese_burger['add_cucumber']()  # adding cucumber...
    trivia_beef_cheese_burger['add_ketchup']()  # adding ketchup...
    trivia_beef_cheese_burger['add_hot_sauce']()  # adding hot sauce...
    trivia_beef_cheese_burger['add_bun_bread']()  # adding bun bread...
    trivia_beef_cheese_burger['serve']()  # ready to serve!

    eunice_beef_cheese_burger = create_egg_cheese_burger()
    eunice_beef_cheese_burger['prepare']()  # preparing...
    eunice_beef_cheese_burger['add_bun_bread']()  # adding bun bread...
    eunice_beef_cheese_burger['butter']()  # buttering...
    eunice_beef_cheese_burger['add_egg']()  # adding egg...
    eunice_beef_cheese_burger['fry']()  # frying...
    eunice_beef_cheese_burger['add_cheese']()  # adding cheese...
    eunice_beef_cheese_burger['add_lettuce']()  # adding lettuce...
    eunice_beef_cheese_burger['add_tomatto']()  # adding tomatto...
    eunice_beef_cheese_burger['add_onion']()  # adding onion...
    eunice_beef_cheese_burger['add_cucumber']()  # adding cucumber...
    eunice_beef_cheese_burger['add_ketchup']()  # adding ketchup...
    eunice_beef_cheese_burger['add_hot_sauce']()  # adding hot sauce...
    eunice_beef_cheese_burger['add_bun_bread']()  # adding bun bread...
    eunice_beef_cheese_burger['serve']()  # ready to serve!

    angel_hot_dog = create_ordinary_hotdog()
    angel_hot_dog['prepare']()  # preparing...
    angel_hot_dog['add_long_bread']()  # adding long bread...
    angel_hot_dog['butter']()  # buttering...
    angel_hot_dog['add_sausage']()  # adding sausage...
    angel_hot_dog['fry']()  # frying...
    angel_hot_dog['add_hot_sauce']()  # adding hot sauce...
    angel_hot_dog['add_ketchup']()  # adding ketchup...
    angel_hot_dog['add_mayonnaise']()  # adding mayonnaise...
    angel_hot_dog['serve']()  # ready to serve!


if __name__ == '__main__':
    python_composition()
