<?php
    $php_composition = function() {
        echo('Composition in PHP<br /><br />');

        $preparing = fn() => ['prepare' => function() {
            echo('preparing...<br />');
        }];
        $serving = fn() => ['serve' => function() {
            echo('ready to serve!<br /><br />');
        }];
        $buttering = fn() => ['butter' => function() {
            echo('buttering...<br />');
        }];
        $adding_flat_bread = fn() => ['add_flat_bread' => function() {
            echo('adding flat bread...<br />');
        }];
        $adding_bun_bread = fn() => ['add_bun_bread' => function() {
            echo('adding bun bread...<br />');
        }];
        $adding_long_bread = fn() => ['add_long_bread' => function() {
            echo('adding long bread...<br />');
        }];
        $adding_sausage = fn() => ['add_sausage' => function() {
            echo('adding sausage...<br />');
        }];
        $adding_hot_sauce = fn() => ['add_hot_sauce' => function() {
            echo('adding hot sauce...<br />');
        }];
        $adding_ketchup = fn() => ['add_ketchup' => function() {
            echo('adding ketchup...<br />');
        }];
        $adding_mayonnaise = fn() => ['add_mayonnaise' => function() {
            echo('adding mayonnaise...<br />');
        }];
        $adding_mushroom = fn() => ['add_mushroom' => function() {
            echo('adding mushroom...<br />');
        }];
        $adding_cheese = fn() => ['add_cheese' => function() {
            echo('adding cheese...<br />');
        }];
        $adding_beef_patty = fn() => ['add_beef_patty' => function() {
            echo('adding beef patty...<br />');
        }];
        $adding_egg = fn() => ['add_egg' => function() {
            echo('adding egg...<br />');
        }];
        $adding_lettuce = fn() => ['add_lettuce' => function() {
            echo('adding lettuce...<br />');
        }];
        $adding_tomatto = fn() => ['add_tomatto' => function() {
            echo('adding tomatto...<br />');
        }];
        $adding_cucumber = fn() => ['add_cucumber' => function() {
            echo('adding cucumber...<br />');
        }];
        $adding_onion = fn() => ['add_onion' => function() {
            echo('adding onion...<br />');
        }];
        $baking = fn() => ['bake' => function() {
            echo('baking...<br />');
        }];
        $frying = fn() => ['fry' => function() {
            echo('frying...<br />');
        }];

        $create_ordinary_pizza = fn() => [...$preparing(), ...$adding_flat_bread(), ...$buttering(), ...$serving()];
        $create_ordinary_burger = fn() => [...$preparing(), ...$adding_bun_bread(), ...$buttering(), ...$serving()];
        $create_ordinary_hotdog = fn() => [...$preparing(), ...$adding_long_bread(), ...$buttering(), ...$adding_sausage(), ...$frying(), ...$adding_hot_sauce(), ...$adding_ketchup(), ...$adding_mayonnaise(), ...$serving()];
        $create_sausage_cheese_pizza = fn() => [...$create_ordinary_pizza(), ...$adding_sausage(), ...$frying(), ...$adding_cheese(), ...$adding_ketchup(), ...$adding_hot_sauce()];
        $create_sausage_mushroom_cheese_pizza = fn() => [...$create_ordinary_pizza(), ...$adding_sausage(), ...$frying(), ...$adding_mushroom(), ...$adding_cheese(), ...$adding_ketchup(), ...$adding_hot_sauce()];
        $create_sausage_mushroom_beef_cheese_pizza = fn() => [...$create_ordinary_pizza(), ...$adding_sausage(), ...$frying(), ...$adding_beef_patty(), ...$frying(), ...$adding_mushroom(), ...$adding_cheese(), ...$adding_ketchup(), ...$adding_hot_sauce()];
        $create_beef_cheese_burger = fn() => [...$create_ordinary_burger(), ...$adding_beef_patty(), ...$frying(), ...$adding_cheese(), ...$adding_lettuce(), ...$adding_tomatto(), ...$adding_onion(), ...$adding_cucumber(), ...$adding_ketchup(), ...$adding_hot_sauce()];
        $create_egg_cheese_burger = fn() => [...$create_ordinary_burger(), ...$adding_egg(), ...$frying(), ...$adding_cheese(), ...$adding_lettuce(), ...$adding_tomatto(), ...$adding_onion(), ...$adding_cucumber(), ...$adding_ketchup(), ...$adding_hot_sauce()];

        $daves_sausage_cheese_pizza = $create_sausage_cheese_pizza();
        $daves_sausage_cheese_pizza['prepare'](); // preparing...
        $daves_sausage_cheese_pizza['add_flat_bread'](); // adding flat bread...
        $daves_sausage_cheese_pizza['butter'](); // buttering...
        $daves_sausage_cheese_pizza['add_sausage'](); // adding sausage...
        $daves_sausage_cheese_pizza['fry'](); // frying...
        $daves_sausage_cheese_pizza['add_cheese'](); // adding cheese...
        $daves_sausage_cheese_pizza['add_ketchup'](); // adding ketchup...
        $daves_sausage_cheese_pizza['add_hot_sauce'](); // adding hot sauce...
        $daves_sausage_cheese_pizza['serve'](); // ready to serve!

        $alisa_sausage_cheese_pizza = $create_sausage_cheese_pizza();
        $alisa_sausage_cheese_pizza['prepare'](); // preparing...
        $alisa_sausage_cheese_pizza['add_flat_bread'](); // adding flat bread...
        $alisa_sausage_cheese_pizza['butter'](); // buttering...
        $alisa_sausage_cheese_pizza['add_sausage'](); // adding sausage...
        $alisa_sausage_cheese_pizza['fry'](); // frying...
        $alisa_sausage_cheese_pizza['add_cheese'](); // adding cheese...
        $alisa_sausage_cheese_pizza['add_ketchup'](); // adding ketchup...
        $alisa_sausage_cheese_pizza['add_hot_sauce'](); // adding hot sauce...
        $alisa_sausage_cheese_pizza['serve'](); // ready to serve!

        $trivia_beef_cheese_burger = $create_beef_cheese_burger();
        $trivia_beef_cheese_burger['prepare'](); // preparing...
        $trivia_beef_cheese_burger['add_bun_bread'](); // adding bun bread...
        $trivia_beef_cheese_burger['butter'](); // buttering...
        $trivia_beef_cheese_burger['add_beef_patty'](); // adding beef patty...
        $trivia_beef_cheese_burger['fry'](); // frying...
        $trivia_beef_cheese_burger['add_cheese'](); // adding cheese...
        $trivia_beef_cheese_burger['add_lettuce'](); // adding lettuce...
        $trivia_beef_cheese_burger['add_tomatto'](); // adding tomatto...
        $trivia_beef_cheese_burger['add_onion'](); // adding onion...
        $trivia_beef_cheese_burger['add_cucumber'](); // adding cucumber...
        $trivia_beef_cheese_burger['add_ketchup'](); // adding ketchup...
        $trivia_beef_cheese_burger['add_hot_sauce'](); // adding hot sauce...
        $trivia_beef_cheese_burger['add_bun_bread'](); // adding bun bread...
        $trivia_beef_cheese_burger['serve'](); // ready to serve!

        $eunice_beef_cheese_burger = $create_egg_cheese_burger();
        $eunice_beef_cheese_burger['prepare'](); // preparing...
        $eunice_beef_cheese_burger['add_bun_bread'](); // adding bun bread...
        $eunice_beef_cheese_burger['butter'](); // buttering...
        $eunice_beef_cheese_burger['add_egg'](); // adding egg...
        $eunice_beef_cheese_burger['fry'](); // frying...
        $eunice_beef_cheese_burger['add_cheese'](); // adding cheese...
        $eunice_beef_cheese_burger['add_lettuce'](); // adding lettuce...
        $eunice_beef_cheese_burger['add_tomatto'](); // adding tomatto...
        $eunice_beef_cheese_burger['add_onion'](); // adding onion...
        $eunice_beef_cheese_burger['add_cucumber'](); // adding cucumber...
        $eunice_beef_cheese_burger['add_ketchup'](); // adding ketchup...
        $eunice_beef_cheese_burger['add_hot_sauce'](); // adding hot sauce...
        $eunice_beef_cheese_burger['add_bun_bread'](); // adding bun bread...
        $eunice_beef_cheese_burger['serve'](); // ready to serve!

        $angel_hot_dog = $create_ordinary_hotdog();
        $angel_hot_dog['prepare'](); // preparing...
        $angel_hot_dog['add_long_bread'](); // adding long bread...
        $angel_hot_dog['butter'](); // buttering...
        $angel_hot_dog['add_sausage'](); // adding sausage...
        $angel_hot_dog['fry'](); // frying...
        $angel_hot_dog['add_hot_sauce'](); // adding hot sauce...
        $angel_hot_dog['add_ketchup'](); // adding ketchup...
        $angel_hot_dog['add_mayonnaise'](); // adding mayonnaise...
        $angel_hot_dog['serve'](); // ready to serve!
    };
?>