<?php
    $php_composition = function() {
        echo('Composition in PHP<br /><br />');

        $preparing = fn() => ['prepare' => function() {
            echo('Preparing...<br />');
        }];
        $serving = fn() => ['serve' => function() {
            echo('Ready to serve!<br /><br />');
        }];
        $buttering = fn() => ['butter' => function() {
            echo('Buttering...<br />');
        }];
        $addingFlatBread = fn() => ['addFlatBread' => function() {
            echo('Adding flat bread...<br />');
        }];
        $addingBunBread = fn() => ['addBunBread' => function() {
            echo('Adding bun bread...<br />');
        }];
        $addingLongBread = fn() => ['addLongBread' => function() {
            echo('Adding long bread...<br />');
        }];
        $addingSausage = fn() => ['addSausage' => function() {
            echo('Adding sausage...<br />');
        }];
        $addingHotSauce = fn() => ['addHotSauce' => function() {
            echo('Adding hot sauce...<br />');
        }];
        $addingKetchup = fn() => ['addKetchup' => function() {
            echo('Adding ketchup...<br />');
        }];
        $addingMayonnaise = fn() => ['addMayonnaise' => function() {
            echo('Adding mayonnaise...<br />');
        }];
        $addingMushroom = fn() => ['addMushroom' => function() {
            echo('Adding mushroom...<br />');
        }];
        $addingCheese = fn() => ['addCheese' => function() {
            echo('Adding cheese...<br />');
        }];
        $addingBeefPatty = fn() => ['addBeefPatty' => function() {
            echo('Adding beef patty...<br />');
        }];
        $addingEgg = fn() => ['addEgg' => function() {
            echo('Adding egg...<br />');
        }];
        $addingLettuce = fn() => ['addLettuce' => function() {
            echo('Adding lettuce...<br />');
        }];
        $addingTomatto = fn() => ['addTomatto' => function() {
            echo('Adding tomatto...<br />');
        }];
        $addingCucumber = fn() => ['addCucumber' => function() {
            echo('Adding cucumber...<br />');
        }];
        $addingOnion = fn() => ['addOnion' => function() {
            echo('Adding onion...<br />');
        }];
        $baking = fn() => ['bake' => function() {
            echo('Baking...<br />');
        }];
        $frying = fn() => ['fry' => function() {
            echo('Frying...<br />');
        }];

        $createOrdinaryPizza = fn() => [...$preparing(), ...$addingFlatBread(), ...$buttering(), ...$serving()];
        $createOrdinaryBurger = fn() => [...$preparing(), ...$addingBunBread(), ...$buttering(), ...$serving()];
        $createOrdinaryHotdog = fn() => [...$preparing(), ...$addingLongBread(), ...$buttering(), ...$addingSausage(), ...$frying(), ...$addingHotSauce(), ...$addingKetchup(), ...$addingMayonnaise(), ...$serving()];
        $createSausageCheesePizza = fn() => [...$createOrdinaryPizza(), ...$addingSausage(), ...$frying(), ...$addingCheese(), ...$addingKetchup(), ...$addingHotSauce()];
        $createSausageMushroomCheesePizza = fn() => [...$createOrdinaryPizza(), ...$addingSausage(), ...$frying(), ...$addingMushroom(), ...$addingCheese(), ...$addingKetchup(), ...$addingHotSauce()];
        $createSausageMushroomBeefCheesePizza = fn() => [...$createOrdinaryPizza(), ...$addingSausage(), ...$frying(), ...$addingBeefPatty(), ...$frying(), ...$addingMushroom(), ...$addingCheese(), ...$addingKetchup(), ...$addingHotSauce()];
        $createBeefCheeseBurger = fn() => [...$createOrdinaryBurger(), ...$addingBeefPatty(), ...$frying(), ...$addingCheese(), ...$addingLettuce(), ...$addingTomatto(), ...$addingOnion(), ...$addingCucumber(), ...$addingKetchup(), ...$addingHotSauce()];
        $createEggCheeseBurger = fn() => [...$createOrdinaryBurger(), ...$addingEgg(), ...$frying(), ...$addingCheese(), ...$addingLettuce(), ...$addingTomatto(), ...$addingOnion(), ...$addingCucumber(), ...$addingKetchup(), ...$addingHotSauce()];

        $davesSausageCheesePizza = $createSausageCheesePizza();
        $davesSausageCheesePizza['prepare'](); // Preparing...
        $davesSausageCheesePizza['addFlatBread'](); // Adding flat bread...
        $davesSausageCheesePizza['butter'](); // Buttering...
        $davesSausageCheesePizza['addSausage'](); // Adding sausage...
        $davesSausageCheesePizza['fry'](); // Frying...
        $davesSausageCheesePizza['addCheese'](); // Adding cheese...
        $davesSausageCheesePizza['addKetchup'](); // Adding ketchup...
        $davesSausageCheesePizza['addHotSauce'](); // Adding hot sauce...
        $davesSausageCheesePizza['serve'](); // Ready to serve!

        $alisaSausageCheesePizza = $createSausageCheesePizza();
        $alisaSausageCheesePizza['prepare'](); // Preparing...
        $alisaSausageCheesePizza['addFlatBread'](); // Adding flat bread...
        $alisaSausageCheesePizza['butter'](); // Buttering...
        $alisaSausageCheesePizza['addSausage'](); // Adding sausage...
        $alisaSausageCheesePizza['fry'](); // Frying...
        $alisaSausageCheesePizza['addCheese'](); // Adding cheese...
        $alisaSausageCheesePizza['addKetchup'](); // Adding ketchup...
        $alisaSausageCheesePizza['addHotSauce'](); // Adding hot sauce...
        $alisaSausageCheesePizza['serve'](); // Ready to serve!

        $triviaBeefCheeseBurger = $createBeefCheeseBurger();
        $triviaBeefCheeseBurger['prepare'](); // Preparing...
        $triviaBeefCheeseBurger['addBunBread'](); // Adding bun bread...
        $triviaBeefCheeseBurger['butter'](); // Buttering...
        $triviaBeefCheeseBurger['addBeefPatty'](); // Adding beef patty...
        $triviaBeefCheeseBurger['fry'](); // Frying...
        $triviaBeefCheeseBurger['addCheese'](); // Adding cheese...
        $triviaBeefCheeseBurger['addLettuce'](); // Adding lettuce...
        $triviaBeefCheeseBurger['addTomatto'](); // Adding tomatto...
        $triviaBeefCheeseBurger['addOnion'](); // Adding onion...
        $triviaBeefCheeseBurger['addCucumber'](); // Adding cucumber...
        $triviaBeefCheeseBurger['addKetchup'](); // Adding ketchup...
        $triviaBeefCheeseBurger['addHotSauce'](); // Adding hot sauce...
        $triviaBeefCheeseBurger['addBunBread'](); // Adding bun bread...
        $triviaBeefCheeseBurger['serve'](); // Ready to serve!

        $euniceBeefCheeseBurger = $createEggCheeseBurger();
        $euniceBeefCheeseBurger['prepare'](); // Preparing...
        $euniceBeefCheeseBurger['addBunBread'](); // Adding bun bread...
        $euniceBeefCheeseBurger['butter'](); // Buttering...
        $euniceBeefCheeseBurger['addEgg'](); // Adding egg...
        $euniceBeefCheeseBurger['fry'](); // Frying...
        $euniceBeefCheeseBurger['addCheese'](); // Adding cheese...
        $euniceBeefCheeseBurger['addLettuce'](); // Adding lettuce...
        $euniceBeefCheeseBurger['addTomatto'](); // Adding tomatto...
        $euniceBeefCheeseBurger['addOnion'](); // Adding onion...
        $euniceBeefCheeseBurger['addCucumber'](); // Adding cucumber...
        $euniceBeefCheeseBurger['addKetchup'](); // Adding ketchup...
        $euniceBeefCheeseBurger['addHotSauce'](); // Adding hot sauce...
        $euniceBeefCheeseBurger['addBunBread'](); // Adding bun bread...
        $euniceBeefCheeseBurger['serve'](); // Ready to serve!

        $angelHotDog = $createOrdinaryHotdog();
        $angelHotDog['prepare'](); // Preparing...
        $angelHotDog['addLongBread'](); // Adding long bread...
        $angelHotDog['butter'](); // Buttering...
        $angelHotDog['addSausage'](); // Adding sausage...
        $angelHotDog['fry'](); // Frying...
        $angelHotDog['addHotSauce'](); // Adding hot sauce...
        $angelHotDog['addKetchup'](); // Adding ketchup...
        $angelHotDog['addMayonnaise'](); // Adding mayonnaise...
        $angelHotDog['serve'](); // Ready to serve!
    };
?>